<?php

namespace Database\Seeders;

use App\Models\DashboardStatistic;
use Illuminate\Database\Seeder;

class DashboardStatisticSeeder extends Seeder
{
    public function run(): void
    {
        $statistics = [
            // АКАДЕМИЧЕСКАЯ ДЕЯТЕЛЬНОСТЬ
            [
                'key' => 'academic_specialties',
                'category' => 'academic',
                'value' => '15',
                'formatted_value' => '15',
                'formatted_growth' => '+7.1%',
                'label' => 'Специальности',
                'description' => 'Общее количество специальностей в колледже',
                'auto_calculate_growth' => true,
                'previous_value' => 14,
                'order' => 1,
            ],
            [
                'key' => 'academic_distance_learning',
                'category' => 'academic',
                'value' => '65',
                'formatted_value' => '65',
                'formatted_growth' => '+12.1%',
                'label' => 'Поступившие на дистанционное обучение',
                'description' => 'Количество студентов на дистанционном обучении',
                'auto_calculate_growth' => true,
                'previous_value' => 58,
                'order' => 2,
            ],
            [
                'key' => 'academic_foreign_students',
                'category' => 'academic',
                'value' => '89',
                'formatted_value' => '89',
                'formatted_growth' => '+27.1%',
                'label' => 'Иностранные студенты',
                'description' => 'Обучающиеся иностранные граждане',
                'auto_calculate_growth' => true,
                'previous_value' => 70,
                'order' => 3,
            ],
            [
                'key' => 'academic_honors_diplomas',
                'category' => 'academic',
                'value' => '42',
                'formatted_value' => '42',
                'formatted_growth' => '+10.5%',
                'label' => 'Дипломы с отличием',
                'description' => 'Окончившие колледж с дипломом с отличием',
                'auto_calculate_growth' => true,
                'previous_value' => 38,
                'order' => 4,
            ],
            [
                'key' => 'academic_work_qualification',
                'category' => 'academic',
                'value' => '3530',
                'formatted_value' => '3 530',
                'formatted_growth' => '+3.2%',
                'label' => 'Рабочая квалификация',
                'description' => 'Количество обучающихся по программе рабочей квалификации',
                'auto_calculate_growth' => true,
                'previous_value' => 3420,
                'order' => 5,
            ],
            [
                'key' => 'academic_mid_specialist',
                'category' => 'academic',
                'value' => '1170',
                'formatted_value' => '1 170',
                'formatted_growth' => '+1.7%',
                'label' => 'Специалист среднего звена',
                'description' => 'Количество обучающихся по программе специалиста среднего звена',
                'auto_calculate_growth' => true,
                'previous_value' => 1150,
                'order' => 6,
            ],
            [
                'key' => 'academic_applied_bachelor',
                'category' => 'academic',
                'value' => '177',
                'formatted_value' => '177',
                'formatted_growth' => '+7.3%',
                'label' => 'Прикладной бакалавр',
                'description' => 'Количество обучающихся по программе прикладного бакалавра',
                'auto_calculate_growth' => true,
                'previous_value' => 165,
                'order' => 7,
            ],
            [
                'key' => 'academic_dual_learning_coverage',
                'category' => 'academic',
                'value' => '82',
                'formatted_value' => '82%',
                'formatted_growth' => '+5.1%',
                'label' => 'Охват дуальным обучением',
                'description' => 'Процент охвата дуальным обучением от ГЗ',
                'auto_calculate_growth' => true,
                'previous_value' => 78,
                'order' => 8,
            ],
            [
                'key' => 'academic_teachers_advanced_training',
                'category' => 'academic',
                'value' => '12',
                'formatted_value' => '12',
                'formatted_growth' => '+20.0%',
                'label' => 'Преподаватели прошли повышение квалификации',
                'description' => 'Количество преподавателей, прошедших повышение квалификации',
                'auto_calculate_growth' => true,
                'previous_value' => 10,
                'order' => 9,
            ],
            [
                'key' => 'academic_contests_first',
                'category' => 'academic',
                'value' => '8',
                'formatted_value' => '8',
                'formatted_growth' => '+14.3%',
                'label' => 'Первые места в конкурсах',
                'description' => 'Конкурсы профмастерства - 1 места',
                'auto_calculate_growth' => true,
                'previous_value' => 7,
                'order' => 10,
            ],
            [
                'key' => 'academic_contests_second',
                'category' => 'academic',
                'value' => '12',
                'formatted_value' => '12',
                'formatted_growth' => '+9.1%',
                'label' => 'Вторые места в конкурсах',
                'description' => 'Конкурсы профмастерства - 2 места',
                'auto_calculate_growth' => true,
                'previous_value' => 11,
                'order' => 11,
            ],
            [
                'key' => 'academic_contests_third',
                'category' => 'academic',
                'value' => '15',
                'formatted_value' => '15',
                'formatted_growth' => '+7.1%',
                'label' => 'Третьи места в конкурсах',
                'description' => 'Конкурсы профмастерства - 3 места',
                'auto_calculate_growth' => true,
                'previous_value' => 14,
                'order' => 12,
            ],
            [
                'key' => 'academic_contests_medals',
                'category' => 'academic',
                'value' => '6',
                'formatted_value' => '6',
                'formatted_growth' => '+20.0%',
                'label' => 'Медальоны',
                'description' => 'Конкурсы профмастерства - медальоны',
                'auto_calculate_growth' => true,
                'previous_value' => 5,
                'order' => 13,
            ],
            [
                'key' => 'academic_ipr_masters',
                'category' => 'academic',
                'value' => '28',
                'formatted_value' => '28',
                'formatted_growth' => '+7.7%',
                'label' => 'ИПР с магистерской степенью',
                'description' => 'Количество ИПР с магистерской степенью',
                'auto_calculate_growth' => true,
                'previous_value' => 26,
                'order' => 14,
            ],
            [
                'key' => 'academic_ipr_category',
                'category' => 'academic',
                'value' => '35',
                'formatted_value' => '35',
                'formatted_growth' => '+6.1%',
                'label' => 'ИПР с категорией',
                'description' => 'Количество ИПР с категорией',
                'auto_calculate_growth' => true,
                'previous_value' => 33,
                'order' => 15,
            ],
            [
                'key' => 'academic_basic_level',
                'category' => 'academic',
                'value' => '17',
                'formatted_value' => '17',
                'formatted_growth' => '-5.6%',
                'label' => 'ИПР базовый уровень',
                'description' => 'Количество ИПР базового уровня',
                'auto_calculate_growth' => true,
                'previous_value' => 18,
                'order' => 16,
            ],
            [
                'key' => 'academic_total_ipr',
                'category' => 'academic',
                'value' => '80',
                'formatted_value' => '80',
                'formatted_growth' => null,
                'label' => 'Всего ИПР',
                'description' => 'Общее количество ИПР',
                'auto_calculate_growth' => false,
                'order' => 17,
            ],
            [
                'key' => 'academic_commercialization',
                'category' => 'academic',
                'value' => '15500000',
                'formatted_value' => '15.5 млн ₸',
                'formatted_growth' => '+9.2%',
                'label' => 'Коммерциализация',
                'description' => 'Доходы от коммерциализации',
                'auto_calculate_growth' => true,
                'previous_value' => 14200000,
                'order' => 18,
            ],
            [
                'key' => 'academic_endowment_fund',
                'category' => 'academic',
                'value' => '8200000',
                'formatted_value' => '8.2 млн ₸',
                'formatted_growth' => '+5.1%',
                'label' => 'Эндаумент фонд',
                'description' => 'Средства эндаумент фонда',
                'auto_calculate_growth' => true,
                'previous_value' => 7800000,
                'order' => 19,
            ],
            [
                'key' => 'academic_laboratories_count',
                'category' => 'academic',
                'value' => '12',
                'formatted_value' => '12',
                'formatted_growth' => '+9.1%',
                'label' => 'Количество лабораторий',
                'description' => 'Общее количество лабораторий',
                'auto_calculate_growth' => true,
                'previous_value' => 11,
                'order' => 20,
            ],
            [
                'key' => 'academic_contingent_gz',
                'category' => 'academic',
                'value' => '2500',
                'formatted_value' => '2 500',
                'formatted_growth' => '+2.0%',
                'label' => 'Контингент ГЗ',
                'description' => 'Количество студентов на госзаказе',
                'auto_calculate_growth' => true,
                'previous_value' => 2450,
                'order' => 21,
            ],
            [
                'key' => 'academic_contingent_cgz',
                'category' => 'academic',
                'value' => '800',
                'formatted_value' => '800',
                'formatted_growth' => '+2.6%',
                'label' => 'Контингент ЦГЗ',
                'description' => 'Количество студентов на целевом госзаказе',
                'auto_calculate_growth' => true,
                'previous_value' => 780,
                'order' => 22,
            ],
            [
                'key' => 'academic_contingent_paid',
                'category' => 'academic',
                'value' => '577',
                'formatted_value' => '577',
                'formatted_growth' => '+3.0%',
                'label' => 'Контингент платно',
                'description' => 'Количество студентов на платном обучении',
                'auto_calculate_growth' => true,
                'previous_value' => 560,
                'order' => 23,
            ],
            [
                'key' => 'admission_gz',
                'category' => 'academic',
                'value' => '150',
                'formatted_value' => '150',
                'formatted_growth' => '+3.4%',
                'label' => 'Новый прием ГЗ',
                'description' => 'Количество новых студентов на госзаказе',
                'auto_calculate_growth' => true,
                'previous_value' => 145,
                'order' => 24,
            ],
            [
                'key' => 'admission_cgz',
                'category' => 'academic',
                'value' => '50',
                'formatted_value' => '50',
                'formatted_growth' => '+4.2%',
                'label' => 'Новый прием ЦГЗ',
                'description' => 'Количество новых студентов на целевом госзаказе',
                'auto_calculate_growth' => true,
                'previous_value' => 48,
                'order' => 25,
            ],
            [
                'key' => 'admission_paid',
                'category' => 'academic',
                'value' => '12',
                'formatted_value' => '12',
                'formatted_growth' => '+9.1%',
                'label' => 'Новый прием платно',
                'description' => 'Количество новых платных студентов',
                'auto_calculate_growth' => true,
                'previous_value' => 11,
                'order' => 26,
            ],
            [
                'key' => 'employment_employed',
                'category' => 'academic',
                'value' => '81',
                'formatted_value' => '81',
                'formatted_growth' => '+3.8%',
                'label' => 'Трудоустроены',
                'description' => 'Выпускники, которые трудоустроены',
                'auto_calculate_growth' => true,
                'previous_value' => 78,
                'order' => 27,
            ],
            [
                'key' => 'employment_studying',
                'category' => 'academic',
                'value' => '15',
                'formatted_value' => '15',
                'formatted_growth' => '+7.1%',
                'label' => 'Учёба/декрет/армия',
                'description' => 'Выпускники, которые продолжают учёбу или в декрете/армии',
                'auto_calculate_growth' => true,
                'previous_value' => 14,
                'order' => 28,
            ],
            [
                'key' => 'employment_unemployed',
                'category' => 'academic',
                'value' => '4',
                'formatted_value' => '4',
                'formatted_growth' => '-20.0%',
                'label' => 'Не трудоустроены',
                'description' => 'Выпускники, которые не трудоустроены',
                'auto_calculate_growth' => true,
                'previous_value' => 5,
                'order' => 29,
            ],

            // ДАННЫЕ ДЛЯ ГРАФИКА "СТУДЕНТЫ ПО ОТДЕЛЕНИЯМ И УРОВНЯМ"
            // Рабочая квалификация по отделениям
            [
                'key' => 'departments_work_qualification_op',
                'category' => 'academic',
                'value' => '1000',
                'formatted_value' => '1 000',
                'formatted_growth' => '+2.0%',
                'label' => 'Рабочая квалификация - ОП, АТ и С',
                'description' => 'Количество студентов рабочей квалификации в отделении ОП, АТ и С',
                'auto_calculate_growth' => true,
                'previous_value' => 980,
                'order' => 30,
            ],
            [
                'key' => 'departments_work_qualification_vh',
                'category' => 'academic',
                'value' => '800',
                'formatted_value' => '800',
                'formatted_growth' => '+2.6%',
                'label' => 'Рабочая квалификация - ВХ и ПХ, АД',
                'description' => 'Количество студентов рабочей квалификации в отделении ВХ и ПХ, АД',
                'auto_calculate_growth' => true,
                'previous_value' => 780,
                'order' => 31,
            ],
            [
                'key' => 'departments_work_qualification_it',
                'category' => 'academic',
                'value' => '600',
                'formatted_value' => '600',
                'formatted_growth' => '+3.4%',
                'label' => 'Рабочая квалификация - IT отделение',
                'description' => 'Количество студентов рабочей квалификации в IT отделении',
                'auto_calculate_growth' => true,
                'previous_value' => 580,
                'order' => 32,
            ],
            [
                'key' => 'departments_work_qualification_ozo',
                'category' => 'academic',
                'value' => '400',
                'formatted_value' => '400',
                'formatted_growth' => '+2.6%',
                'label' => 'Рабочая квалификация - ОЗО',
                'description' => 'Количество студентов рабочей квалификации на ОЗО',
                'auto_calculate_growth' => true,
                'previous_value' => 390,
                'order' => 33,
            ],

            // Специалист среднего звена по отделениям
            [
                'key' => 'departments_mid_specialist_op',
                'category' => 'academic',
                'value' => '700',
                'formatted_value' => '700',
                'formatted_growth' => '+2.9%',
                'label' => 'Специалист среднего звена - ОП, АТ и С',
                'description' => 'Количество студентов специалиста среднего звена в отделении ОП, АТ и С',
                'auto_calculate_growth' => true,
                'previous_value' => 680,
                'order' => 34,
            ],
            [
                'key' => 'departments_mid_specialist_vh',
                'category' => 'academic',
                'value' => '600',
                'formatted_value' => '600',
                'formatted_growth' => '+1.7%',
                'label' => 'Специалист среднего звена - ВХ и ПХ, АД',
                'description' => 'Количество студентов специалиста среднего звена в отделении ВХ и ПХ, АД',
                'auto_calculate_growth' => true,
                'previous_value' => 590,
                'order' => 35,
            ],
            [
                'key' => 'departments_mid_specialist_it',
                'category' => 'academic',
                'value' => '300',
                'formatted_value' => '300',
                'formatted_growth' => '+3.4%',
                'label' => 'Специалист среднего звена - IT отделение',
                'description' => 'Количество студентов специалиста среднего звена в IT отделении',
                'auto_calculate_growth' => true,
                'previous_value' => 290,
                'order' => 36,
            ],
            [
                'key' => 'departments_mid_specialist_ozo',
                'category' => 'academic',
                'value' => '200',
                'formatted_value' => '200',
                'formatted_growth' => '+2.6%',
                'label' => 'Специалист среднего звена - ОЗО',
                'description' => 'Количество студентов специалиста среднего звена на ОЗО',
                'auto_calculate_growth' => true,
                'previous_value' => 195,
                'order' => 37,
            ],

            // Прикладной бакалавр по отделениям
            [
                'key' => 'departments_applied_bachelor_op',
                'category' => 'academic',
                'value' => '150',
                'formatted_value' => '150',
                'formatted_growth' => '+7.1%',
                'label' => 'Прикладной бакалавр - ОП, АТ и С',
                'description' => 'Количество студентов прикладного бакалавра в отделении ОП, АТ и С',
                'auto_calculate_growth' => true,
                'previous_value' => 140,
                'order' => 38,
            ],
            [
                'key' => 'departments_applied_bachelor_vh',
                'category' => 'academic',
                'value' => '100',
                'formatted_value' => '100',
                'formatted_growth' => '+5.3%',
                'label' => 'Прикладной бакалавр - ВХ и ПХ, АД',
                'description' => 'Количество студентов прикладного бакалавра в отделении ВХ и ПХ, АД',
                'auto_calculate_growth' => true,
                'previous_value' => 95,
                'order' => 39,
            ],
            [
                'key' => 'departments_applied_bachelor_it',
                'category' => 'academic',
                'value' => '80',
                'formatted_value' => '80',
                'formatted_growth' => '+6.7%',
                'label' => 'Прикладной бакалавр - IT отделение',
                'description' => 'Количество студентов прикладного бакалавра в IT отделении',
                'auto_calculate_growth' => true,
                'previous_value' => 75,
                'order' => 40,
            ],
            [
                'key' => 'departments_applied_bachelor_ozo',
                'category' => 'academic',
                'value' => '50',
                'formatted_value' => '50',
                'formatted_growth' => '+4.2%',
                'label' => 'Прикладной бакалавр - ОЗО',
                'description' => 'Количество студентов прикладного бакалавра на ОЗО',
                'auto_calculate_growth' => true,
                'previous_value' => 48,
                'order' => 41,
            ],

            [
                'key' => 'academic_foreign_language_teachers',
                'category' => 'academic',
                'value' => '42',
                'formatted_value' => '42',
                'formatted_growth' => '+7.7%',
                'label' => 'Преподаватели с иностранными языками',
                'description' => 'Преподаватели, владеющие иностранными языками',
                'auto_calculate_growth' => true,
                'previous_value' => 39,
                'order' => 42,
            ],

            // ИДЕОЛОГИЧЕСКАЯ ДЕЯТЕЛЬНОСТЬ (СОБЫТИЯ)
            [
                'key' => 'ideology_sports_sections',
                'category' => 'events',
                'value' => '8',
                'formatted_value' => '8',
                'formatted_growth' => '+14.3%',
                'label' => 'Спортивные секции',
                'description' => 'Количество спортивных секций колледжа',
                'auto_calculate_growth' => true,
                'previous_value' => 7,
                'order' => 1,
            ],
            [
                'key' => 'ideology_sports_students_total',
                'category' => 'events',
                'value' => '420',
                'formatted_value' => '420',
                'formatted_growth' => '+6.3%',
                'label' => 'Студенты в спортивных секциях',
                'description' => 'Общее количество студентов в спортивных секциях',
                'auto_calculate_growth' => true,
                'previous_value' => 395,
                'order' => 2,
            ],
            [
                'key' => 'ideology_dormitory_students',
                'category' => 'events',
                'value' => '320',
                'formatted_value' => '320',
                'formatted_growth' => '+3.2%',
                'label' => 'Студенты в общежитии',
                'description' => 'Количество студентов проживающих в общежитии',
                'auto_calculate_growth' => true,
                'previous_value' => 310,
                'order' => 3,
            ],
            [
                'key' => 'ideology_total_winners',
                'category' => 'events',
                'value' => '85',
                'formatted_value' => '85',
                'formatted_growth' => '+9.0%',
                'label' => 'Призёры соревнований',
                'description' => 'Призеры городских, областных и республиканских соревнований',
                'auto_calculate_growth' => true,
                'previous_value' => 78,
                'order' => 4,
            ],
            [
                'key' => 'social_telegram',
                'category' => 'events',
                'value' => '4052',
                'formatted_value' => '4 052',
                'formatted_growth' => '+1.8%',
                'label' => 'Подписчики Telegram',
                'description' => 'Количество подписчиков в Telegram',
                'auto_calculate_growth' => true,
                'previous_value' => 3980,
                'order' => 5,
            ],
            [
                'key' => 'social_instagram',
                'category' => 'events',
                'value' => '12646',
                'formatted_value' => '12 646',
                'formatted_growth' => '+1.6%',
                'label' => 'Подписчики Instagram',
                'description' => 'Количество подписчиков в Instagram',
                'auto_calculate_growth' => true,
                'previous_value' => 12450,
                'order' => 6,
            ],
            [
                'key' => 'social_youtube',
                'category' => 'events',
                'value' => '1157',
                'formatted_value' => '1 157',
                'formatted_growth' => '+3.3%',
                'label' => 'Подписчики YouTube',
                'description' => 'Количество подписчиков на YouTube',
                'auto_calculate_growth' => true,
                'previous_value' => 1120,
                'order' => 7,
            ],

            // АДМИНИСТРАТИВНАЯ ДЕЯТЕЛЬНОСТЬ (УСЛУГИ)
            [
                'key' => 'admin_average_age',
                'category' => 'services',
                'value' => '42',
                'formatted_value' => '42',
                'formatted_growth' => null,
                'label' => 'Средний возраст ИПР',
                'description' => 'Средний возраст инженерно-педагогических работников',
                'auto_calculate_growth' => false,
                'order' => 1,
            ],
            [
                'key' => 'admin_digital_library',
                'category' => 'services',
                'value' => '5015',
                'formatted_value' => '5 015',
                'formatted_growth' => '+2.5%',
                'label' => 'Фонд электронной библиотеки',
                'description' => 'Количество единиц в электронной библиотеке',
                'auto_calculate_growth' => true,
                'previous_value' => 4892,
                'order' => 2,
            ],
            [
                'key' => 'admin_portal_visits',
                'category' => 'services',
                'value' => '985',
                'formatted_value' => '985',
                'formatted_growth' => null,
                'label' => 'Посещения портала сегодня',
                'description' => 'Посещения портала VKEiK.EDU.KZ за сегодня',
                'auto_calculate_growth' => false,
                'is_auto_updated' => true,
                'update_source' => DashboardStatistic::SOURCE_PORTAL_VISITS,
                'order' => 3,
            ],
            [
                'key' => 'admin_cos_appeals',
                'category' => 'services',
                'value' => '352',
                'formatted_value' => '352',
                'formatted_growth' => '+7.3%',
                'label' => 'Обращений в ЦОС за месяц',
                'description' => 'Количество обращений в Центр обслуживания студентов',
                'auto_calculate_growth' => true,
                'previous_value' => 328,
                'order' => 4,
            ],
            [
                'key' => 'admin_blog_appeals',
                'category' => 'services',
                'value' => '128',
                'formatted_value' => '128',
                'formatted_growth' => '+11.3%',
                'label' => 'Обращений в блог руководителя',
                'description' => 'Количество обращений в блог руководителя',
                'auto_calculate_growth' => true,
                'is_auto_updated' => true,
                'update_source' => DashboardStatistic::SOURCE_BLOG_APPEALS,
                'previous_value' => 115,
                'order' => 5,
            ],
            [
                'key' => 'teachers_transport',
                'category' => 'services',
                'value' => '11',
                'formatted_value' => '11',
                'formatted_growth' => '+10.0%',
                'label' => 'Педагоги транспорта',
                'description' => 'Количество педагогов транспортного отделения',
                'auto_calculate_growth' => true,
                'previous_value' => 10,
                'order' => 6,
            ],
            [
                'key' => 'teachers_computers',
                'category' => 'services',
                'value' => '7',
                'formatted_value' => '7',
                'formatted_growth' => '0.0%',
                'label' => 'Педагоги вычислительной техники',
                'description' => 'Количество педагогов вычислительной техники и ПО',
                'auto_calculate_growth' => true,
                'previous_value' => 7,
                'order' => 7,
            ],
            [
                'key' => 'teachers_automation',
                'category' => 'services',
                'value' => '17',
                'formatted_value' => '17',
                'formatted_growth' => '+6.3%',
                'label' => 'Педагоги автоматики',
                'description' => 'Количество педагогов автоматики и организации перевозок',
                'auto_calculate_growth' => true,
                'previous_value' => 16,
                'order' => 8,
            ],
            [
                'key' => 'teachers_sports',
                'category' => 'services',
                'value' => '5',
                'formatted_value' => '5',
                'formatted_growth' => '0.0%',
                'label' => 'Педагоги физкультуры',
                'description' => 'Количество педагогов физкультуры и НВиТП',
                'auto_calculate_growth' => true,
                'previous_value' => 5,
                'order' => 9,
            ],
            [
                'key' => 'teachers_general',
                'category' => 'services',
                'value' => '13',
                'formatted_value' => '13',
                'formatted_growth' => '+8.3%',
                'label' => 'Педагоги общих дисциплин',
                'description' => 'Количество педагогов общеобразовательных дисциплин',
                'auto_calculate_growth' => true,
                'previous_value' => 12,
                'order' => 10,
            ],

            // IT CLUSTER
            [
                'key' => 'it_accounts_students',
                'category' => 'tech',
                'value' => '8596',
                'formatted_value' => '8 596',
                'formatted_growth' => '+2.1%',
                'label' => 'Личные кабинеты студентов',
                'description' => 'Количество активных личных кабинетов студентов',
                'auto_calculate_growth' => true,
                'previous_value' => 8420,
                'order' => 1,
            ],
            [
                'key' => 'it_accounts_teachers',
                'category' => 'tech',
                'value' => '625',
                'formatted_value' => '625',
                'formatted_growth' => '+1.1%',
                'label' => 'Личные кабинеты преподавателей',
                'description' => 'Количество активных личных кабинетов преподавателей',
                'auto_calculate_growth' => true,
                'previous_value' => 618,
                'order' => 2,
            ],
            [
                'key' => 'tech_video_lectures',
                'category' => 'tech',
                'value' => '176',
                'formatted_value' => '176',
                'formatted_growth' => '+4.8%',
                'label' => 'Видеолекции',
                'description' => 'Количество видеолекций в электронной библиотеке',
                'auto_calculate_growth' => true,
                'previous_value' => 168,
                'order' => 3,
            ],
            [
                'key' => 'tech_educational_publications',
                'category' => 'tech',
                'value' => '319',
                'formatted_value' => '319',
                'formatted_growth' => '+4.6%',
                'label' => 'Учебные издания',
                'description' => 'Количество учебных изданий',
                'auto_calculate_growth' => true,
                'previous_value' => 305,
                'order' => 4,
            ],
            [
                'key' => 'tech_mobile_resources',
                'category' => 'tech',
                'value' => '41',
                'formatted_value' => '41',
                'formatted_growth' => '+7.9%',
                'label' => 'Мобильные ресурсы',
                'description' => 'Количество мобильных образовательных ресурсов',
                'auto_calculate_growth' => true,
                'previous_value' => 38,
                'order' => 5,
            ],
            [
                'key' => 'tech_building_students',
                'category' => 'tech',
                'value' => '1934',
                'formatted_value' => '1 934',
                'formatted_growth' => null,
                'label' => 'Студенты в здании (СКУД)',
                'description' => 'Количество студентов в здании по данным СКУД',
                'auto_calculate_growth' => false,
                'order' => 6,
            ],
            [
                'key' => 'tech_building_teachers',
                'category' => 'tech',
                'value' => '341',
                'formatted_value' => '341',
                'formatted_growth' => null,
                'label' => 'Преподаватели в здании (СКУД)',
                'description' => 'Количество преподавателей в здании по данным СКУД',
                'auto_calculate_growth' => false,
                'order' => 7,
            ],
            [
                'key' => 'tech_building_staff',
                'category' => 'tech',
                'value' => '100',
                'formatted_value' => '100',
                'formatted_growth' => null,
                'label' => 'Сотрудники в здании (СКУД)',
                'description' => 'Количество сотрудников в здании по данным СКУД',
                'auto_calculate_growth' => false,
                'order' => 8,
            ],
            [
                'key' => 'tech_building_total',
                'category' => 'tech',
                'value' => '2375',
                'formatted_value' => '2 375',
                'formatted_growth' => null,
                'label' => 'Всего в здании (СКУД)',
                'description' => 'Общее количество людей в здании по данным СКУД',
                'auto_calculate_growth' => false,
                'order' => 9,
            ],
            [
                'key' => 'tech_computer_classes',
                'category' => 'tech',
                'value' => '19',
                'formatted_value' => '19',
                'formatted_growth' => '+5.6%',
                'label' => 'Компьютерные классы',
                'description' => 'Количество компьютерных классов',
                'auto_calculate_growth' => true,
                'previous_value' => 18,
                'order' => 10,
            ],
            [
                'key' => 'tech_educational_pcs',
                'category' => 'tech',
                'value' => '265',
                'formatted_value' => '265',
                'formatted_growth' => '+2.7%',
                'label' => 'ПК в учебном процессе',
                'description' => 'Количество компьютеров используемых в учебном процессе',
                'auto_calculate_growth' => true,
                'previous_value' => 258,
                'order' => 11,
            ],
            [
                'key' => 'tech_wifi_points',
                'category' => 'tech',
                'value' => '73',
                'formatted_value' => '73',
                'formatted_growth' => '+4.3%',
                'label' => 'WiFi точки',
                'description' => 'Количество точек доступа WiFi',
                'auto_calculate_growth' => true,
                'previous_value' => 70,
                'order' => 12,
            ],
            [
                'key' => 'tech_physical_servers',
                'category' => 'tech',
                'value' => '9',
                'formatted_value' => '9',
                'formatted_growth' => '+12.5%',
                'label' => 'Физические серверы',
                'description' => 'Количество физических серверов',
                'auto_calculate_growth' => true,
                'previous_value' => 8,
                'order' => 13,
            ],
            [
                'key' => 'tech_virtual_machines',
                'category' => 'tech',
                'value' => '23',
                'formatted_value' => '23',
                'formatted_growth' => '+9.5%',
                'label' => 'Виртуальные машины',
                'description' => 'Количество виртуальных машин',
                'auto_calculate_growth' => true,
                'previous_value' => 21,
                'order' => 14,
            ],
            [
                'key' => 'tech_it_courses',
                'category' => 'tech',
                'value' => '773',
                'formatted_value' => '773',
                'formatted_growth' => '+3.8%',
                'label' => 'Курсы ИТ',
                'description' => 'Количество пройденных IT курсов',
                'auto_calculate_growth' => true,
                'previous_value' => 745,
                'order' => 15,
            ],
            [
                'key' => 'tech_seminars',
                'category' => 'tech',
                'value' => '16',
                'formatted_value' => '16',
                'formatted_growth' => '+14.3%',
                'label' => 'Семинары',
                'description' => 'Количество проведенных семинаров',
                'auto_calculate_growth' => true,
                'previous_value' => 14,
                'order' => 16,
            ],
            [
                'key' => 'tech_vendors',
                'category' => 'tech',
                'value' => '5',
                'formatted_value' => '5',
                'formatted_growth' => null,
                'label' => 'Вендоров',
                'description' => 'Количество партнеров-вендоров',
                'auto_calculate_growth' => false,
                'order' => 17,
            ],
            [
                'key' => 'tech_it_events',
                'category' => 'tech',
                'value' => '16',
                'formatted_value' => '16',
                'formatted_growth' => '+14.3%',
                'label' => 'ИТ мероприятия',
                'description' => 'Количество проведенных IT мероприятий',
                'auto_calculate_growth' => true,
                'previous_value' => 14,
                'order' => 18,
            ],

            // ДОПОЛНИТЕЛЬНЫЕ ДАННЫЕ ДЛЯ IT CLUSTER
            [
                'key' => 'tech_modern_it_percentage',
                'category' => 'tech',
                'value' => '70',
                'formatted_value' => '70%',
                'formatted_growth' => '+2.9%',
                'label' => 'Доля современной IT-техники',
                'description' => 'Процент современной IT-техники от общего количества',
                'auto_calculate_growth' => true,
                'previous_value' => 68,
                'order' => 19,
            ],
            [
                'key' => 'tech_internet_speed',
                'category' => 'tech',
                'value' => '1',
                'formatted_value' => '1 Gbit/s',
                'formatted_growth' => '+11.1%',
                'label' => 'Скорость интернета',
                'description' => 'Скорость интернет-соединения в колледже',
                'auto_calculate_growth' => true,
                'previous_value' => 0.9,
                'order' => 20,
            ],

            // ДОПОЛНИТЕЛЬНЫЕ ДАННЫЕ ДЛЯ СОЦИАЛЬНЫХ СЕТЕЙ (для графиков)
            [
                'key' => 'social_total_followers',
                'category' => 'events',
                'value' => '17855',
                'formatted_value' => '17 855',
                'formatted_growth' => '+1.8%',
                'label' => 'Всего подписчиков',
                'description' => 'Общее количество подписчиков во всех соцсетях',
                'auto_calculate_growth' => true,
                'previous_value' => 17550,
                'order' => 8,
            ],

            // ДОПОЛНИТЕЛЬНЫЕ ДАННЫЕ ДЛЯ ПОРТАЛА
            [
                'key' => 'portal_month_visitors',
                'category' => 'events',
                'value' => '5842',
                'formatted_value' => '5 842',
                'formatted_growth' => '+3.1%',
                'label' => 'Посетители за месяц',
                'description' => 'Количество уникальных посетителей портала за месяц',
                'auto_calculate_growth' => true,
                'is_auto_updated' => true,
                'update_source' => DashboardStatistic::SOURCE_PORTAL_VISITS,
                'previous_value' => 5667,
                'order' => 9,
            ],
            [
                'key' => 'portal_month_views',
                'category' => 'events',
                'value' => '15679',
                'formatted_value' => '15 679',
                'formatted_growth' => '+4.2%',
                'label' => 'Просмотры за месяц',
                'description' => 'Общее количество просмотров страниц портала за месяц',
                'auto_calculate_growth' => true,
                'is_auto_updated' => true,
                'update_source' => DashboardStatistic::SOURCE_PORTAL_VISITS,
                'previous_value' => 15049,
                'order' => 10,
            ],

            // ДОПОЛНИТЕЛЬНЫЕ ДАННЫЕ ДЛЯ УЧИТЕЛЕЙ (сумма)
            [
                'key' => 'teachers_total',
                'category' => 'services',
                'value' => '53',
                'formatted_value' => '53',
                'formatted_growth' => '+6.0%',
                'label' => 'Всего педагогов',
                'description' => 'Общее количество педагогов предметных и цикловых комиссий',
                'auto_calculate_growth' => true,
                'previous_value' => 50,
                'order' => 11,
            ],

            // ДОПОЛНИТЕЛЬНЫЕ ДАННЫЕ ДЛЯ IPR КАЧЕСТВА
            [
                'key' => 'academic_ipr_researcher',
                'category' => 'academic',
                'value' => '28',
                'formatted_value' => '28',
                'formatted_growth' => '+7.7%',
                'label' => 'Педагог-исследователь',
                'description' => 'Количество педагогов-исследователей',
                'auto_calculate_growth' => true,
                'previous_value' => 26,
                'order' => 43,
            ],
            [
                'key' => 'academic_ipr_expert',
                'category' => 'academic',
                'value' => '35',
                'formatted_value' => '35',
                'formatted_growth' => '+6.1%',
                'label' => 'Педагог-эксперт',
                'description' => 'Количество педагогов-экспертов',
                'auto_calculate_growth' => true,
                'previous_value' => 33,
                'order' => 44,
            ],
            [
                'key' => 'academic_ipr_moderator',
                'category' => 'academic',
                'value' => '17',
                'formatted_value' => '17',
                'formatted_growth' => '-5.6%',
                'label' => 'Педагог-модератор',
                'description' => 'Количество педагогов-модераторов',
                'auto_calculate_growth' => true,
                'previous_value' => 18,
                'order' => 45,
            ],

            // ДОПОЛНИТЕЛЬНЫЕ ДАННЫЕ ДЛЯ ТРУДОУСТРОЙСТВА
            [
                'key' => 'employment_total_graduates',
                'category' => 'academic',
                'value' => '100',
                'formatted_value' => '100',
                'formatted_growth' => '+2.0%',
                'label' => 'Всего выпускников',
                'description' => 'Общее количество выпускников',
                'auto_calculate_growth' => true,
                'previous_value' => 98,
                'order' => 46,
            ],

            // ДОПОЛНИТЕЛЬНЫЕ ДАННЫЕ ДЛЯ ЛИЧНЫХ КАБИНЕТОВ
            [
                'key' => 'it_accounts_total',
                'category' => 'tech',
                'value' => '9221',
                'formatted_value' => '9 221',
                'formatted_growth' => '+2.0%',
                'label' => 'Всего личных кабинетов',
                'description' => 'Общее количество активных личных кабинетов',
                'auto_calculate_growth' => true,
                'previous_value' => 9038,
                'order' => 21,
            ],

            // ДОПОЛНИТЕЛЬНЫЕ ДАННЫЕ ДЛЯ ЭЛЕКТРОННЫХ РЕСУРСОВ
            [
                'key' => 'tech_total_digital_resources',
                'category' => 'tech',
                'value' => '536',
                'formatted_value' => '536',
                'formatted_growth' => '+4.9%',
                'label' => 'Всего электронных ресурсов',
                'description' => 'Общее количество электронных образовательных ресурсов',
                'auto_calculate_growth' => true,
                'previous_value' => 511,
                'order' => 22,
            ],
        ];

        foreach ($statistics as $stat) {
            $model = DashboardStatistic::updateOrCreate(
                ['key' => $stat['key']],
                $stat
            );
            
            if ($model->auto_calculate_growth) {
                $model->calculateGrowth();
                $model->save();
            }
        }

        $this->command->info('✅ Статистики дашборда успешно добавлены!');
    }
}